### ISSUE TITLE
Port all python code to python 3

### ISSUE THREAD

**Issue by huddlej** [EichlerLab/pacbio_variant_caller#17]
Because the pipeline requires snakemake which depends on python 3, the pipeline requires python 2 and 3 to be installed at the same time. This can be frustrating or confusing for people to manage. The simplest solution is to only use python3.

**Comment by paudano** [comment]
SMRT-SV v2 uses a build system to install both python2 and python3, and it specifically calls the correct version for each rule. The user's python environment is not needed.

Closing. This project has been replaced with SMRT-SV v2 (https://github.com/EichlerLab/smrtsv2)
