### ISSUE TITLE
Don't allow empty alignment_reads .fofn files to be created when more batches are requested than can be filled

### ISSUE THREAD

**Issue by huddlej** [EichlerLab/pacbio_variant_caller#38]
If only 98 batches can be created for alignments, for instance, don't create files for batches 99 and 100.

**Comment by paudano** [comment]
Closing. This project has been replaced with SMRT-SV v2 (https://github.com/EichlerLab/smrtsv2).

In the new version, if there are empty batches, they are automatically skipped over.
