### ISSUE TITLE
PrintSNVSupport.py is redundant with bedtools groupby

### ISSUE THREAD

**Issue by huddlej** [EichlerLab/pacbio_variant_caller#39]
In the indel calling section of the variant calling pipeline, the output file "gaps_without_homopolymers.bed" can be created by piping to bedtools groupby -g 1,2,3,4,5 -c 6,6 -o count,collapse instead of running PrintSNVSupport.py.

**Comment by paudano** [comment]
Closing. This project has been replaced with SMRT-SV v2 (https://github.com/EichlerLab/smrtsv2)
