### ISSUE TITLE
Snakemake Error

### ISSUE THREAD

**Issue by microsoftofficeword2003** [EichlerLab/pacbio_variant_caller#52]
I ran 
```
/usr/local/smrtsv/bin/smrtsv.py index reference/sacCer3.fasta
``` 
using the example, but I found the error  
```
snakemake: error: argument --force/-f: ignored explicit argument 'ineAlign'
```
Then I found the problem is caused by the parameter
```
alignment_parameters=-bestn 2 -maxAnchorsPerPosition 100 -advanceExactMatches 10 -affineAlign -affineOpen 100 -affineExtend 0 -insertion 5 -deletion 5 -extend -maxExtendDropoff 50
```
of Snakemake.
So how should I deal with the problem?
Should I ask the developer of snakemake the problem?

The environment of execution:

1.  Ubuntu 14.04.5 LTS
2.  Python 2.7.9
3.  Snakemake 3.9.0

**Comment by huddlej** [comment]
This is definitely a SMRT-SV bug; the alignment parameters for the "align" subcommand should be quoted as they are in the "assemble" subcommand.

Can you pull from master and try running align command again?

**Comment by microsoftofficeword2003** [comment]
Thank you.
The problem doesn't happen at present.

Sorry, I wrote the wrong command last time.
The command is 
```
/usr/local/smrtsv/bin/smrtsv.py align reference/sacCer3.fasta reads.fofn
```

**Comment by huddlej** [comment]
Ok, I'll close this for now, but please let me know if you notice the same problem in the future.
