### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by ldorozco** [EichlerLab/pacbio_variant_caller#56]
I as wondering if SMRT-SV does "joint genotyping" of multiple samples, analogous to what GATK does for SNPs?

Does SMRT-SV do break-point resolution? For example, if I have a population samples with structural variants in the same region, can SMRT-SV use that information to try to figure out the boundaries of the structural variant?

Thank you,

Luz

**Comment by paudano** [comment]
SMRT-SV does not do any joint genotyping. It operates on one sample at a time, and it does not consider a known set of SV calls.

Closing. This project has been replaced with SMRT-SV v2 (https://github.com/EichlerLab/smrtsv2)
