### ISSUE TITLE
Find deletions using smrt-sv

### ISSUE THREAD

**Issue by xzhang2016** [EichlerLab/pacbio_variant_caller#58]
My data is pacbio genomic ccs reads for a rat gene (several fastq files corresponding to different conditions). I used minimap2 to do the alignment and samtools to sort and index (got the corresponding bam files). I want to get the possible deletions from these files. Could you tell me how can I use smrt-sv to do this? I read your tutorial, but I am not sure how to do it for my data. Could you give me the example code?

Thanks,
Xue

**Comment by paudano** [comment]
First, this is an older version of SMRT-SV that has been replaced with SMRT-SV v2:
https://github.com/EichlerLab/smrtsv2

Either version was never run with CCS, but it will probably work. Start with your unmapped CCS read BAM files as if they were any other set of reads. Input that into SMRT-SV (as an FOFN), and run it.

Use the updated SMRT-SV (see link above). If you have questions or problems, you can open a ticket on that repository or contact me about questions (Peter Audano in the Eichler lab at UW).
